# ??JWT?JSON Web Token??????
jwt:
  key: xxxx

# ??Knife4j?????Spring Boot API????????
knife4j:
  # ??????????????Swagger???????
  basic:
    # ????????
    enable: true
    # ??????Swagger?????
    password: xxx
    # ??????Swagger?????
    username: xxx
  # ????Knife4j
  enable: true
  # ??????????????Swagger?????????
  production: false
  # ?????????Knife4j????????
  setting:
    # ?????????Knife4j?????
    language: zh_cn

# ??SpringDoc?????API??
springdoc:
  # ??API???????
  api-docs:
    path: /v3/api-docs
  # ??Swagger UI?????
  swagger-ui:
    # ?????????????
    operations-sorter: alpha
    # ??Swagger UI?????
    path: /swagger-ui.html
    # ?????????????
    tags-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sky

# ?????????
logging:
  # ???????????
  config: classpath:logback-spring.xml
  file:
    # ?????
    name: slf4j-SpringTest
    # ?????????
    path: ./logs
  level:
    # ????????
    com:
      example:
        demo:
          mapper: debug
    # ??????????????
    root: info
  logback:
    rollingpolicy:
      # ??????????
      max-file-size: 1000MB
      # ?????????????
      max-history: 7


# Mybatis-Plus??
mybatis-plus:
  # ?????????
  configuration:
    # ??????????????????Java??
    auto-mapping-behavior: full
    # ?????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ????????????????
    map-underscore-to-camel-case: true
  # Mapper??????
  mapper-locations: classpath:mapper/*.xml


# ??????????
server:
  # ???????????
  port: 8080
  # ??Servlet?????
  servlet:
    # ??????????????
    session:
      timeout: 1800


# ??Snowflake???????????????ID
snowflake:
  datacenterId: 1
  workerId: 1

# ??Spring????????????
spring:
  application:
    name: rabbitmq-proj # ????
  data:
    redis: # Redis??
      database: 0 # Redis?????
      host: 39.100.70.122 # Redis??????
      lettuce:
        pool: # Lettuce????????
          max-active: 32 # ???????
          max-idle: 16 # ???????
          min-idle: 8 # ???????
      password: GbiqFy2s3a # Redis?????
      port: 6379 # Redis?????

  datasource: # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC????
    password: xxx # ?????
    url: jdbc:mysql://xxx:3306/xxx?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&useSSL=false # ?????URL
    username: root # ??????

  elasticsearch: # Elasticsearch??
    uris: 127.0.0.1:9200 # Elasticsearch??URI

  mail: # ??????
    default-encoding: UTF-8 # ????
    host: smtp.qq.com # SMTP??????
    password: xxx # SMTP?????
    properties: # ??????
      mail:
        smtp:
          auth: true # ??SMTP??
          starttls:
            enable: true # ??TLS
            required: true # TLS??
    username: xxx # SMTP??????

  mvc: # Spring MVC??
    static-path-pattern: /** # ????????

  rabbitmq: # RabbitMQ??
    host: xxx # RabbitMQ??????
    password: xxx # RabbitMQ?????
    port: 5672 # RabbitMQ?????
    username: admin # RabbitMQ??????

  servlet: # Servlet??
    multipart: # ?????????
      max-file-size: 16MB # ??????

  web: # Web??
    resources: # ??????
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/,classpath:/public/,classpath:/itstyle/ # ??????


#OSS??
oss:
  endpoint: sts.cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI5t8Tn2AZiJSoztBJ2PEe
  accessKeySecret: ooJoKalkuDHyDz3QkdYdSle1n0sCpG
  roleArn: acs:ram::1320082312507942:role/w
  roleSessionName: RamOssTest
  endpointForOss: oss-cn-shenzhen.aliyuncs.com
  bucketName: videotest5
